### PR TITLE
Updated Tasks Board & Burndown Chart

### PR DESCRIPTION
**Pull request by samehel**

### CODE REVIEW

**Review by ahmednreldin — COMMENTED** [review]
Try to clean up the file , remove old unrelated sections, and add hint for snapshot

**Comment by samehel** [comment]
> Try to clean up the file , remove old unrelated sections, and add hint for snapshot

Done

**Comment by ahmednreldin** [comment]
for task board 
-> this is called Task board in JIRA SW

it have three section and you can add more 
Issue or task  - in progress - done 
image

**Comment by ahmednreldin** [comment]
well done, the last thing I want you to add is a section for tools you used e.g JIRA Software or hint under each snapshot to illustrate what snapshot for

**Review by ahmednreldin — APPROVED** [review]

**Pull request merged**
